DROP DATABASE IF EXISTS flask;
CREATE DATABASE flask;
\c flask;
DROP TABLE IF EXISTS data;
CREATE TABLE data(
  Id BIGSERIAL PRIMARY KEY,
  A INT4,
  B INT4,
  C INT4,
  D VARCHAR(255),
  E VARCHAR(255)
);
